# Generated by Django 4.2.4 on 2023-08-07 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='user',
        ),
        migrations.AddField(
            model_name='components',
            name='client',
            field=models.CharField(default='None', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='priority',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='components',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='components',
            field=models.ManyToManyField(to='core.components'),
        ),
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
