# Generated by Django 4.2.4 on 2023-08-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_components_user_components_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='client',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
