# Generated by Django 4.2.4 on 2023-08-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_projects_user_projects_costing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='costing',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
