# Generated by Django 4.2.4 on 2023-08-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_components_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='components',
            field=models.ManyToManyField(null=True, to='core.components'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(null=True, to='core.tag'),
        ),
    ]
