# Generated by Django 4.2.4 on 2023-08-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_projects_components_alter_projects_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='components',
            field=models.ManyToManyField(blank=True, to='core.components'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
    ]
