# Generated by Django 4.2.4 on 2023-08-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_room_messages_pair_remove_chat_room_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='project',
            new_name='room',
        ),
    ]
