# Generated by Django 4.2.4 on 2023-08-13 05:48

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_pair_messages_room_remove_chat_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='reciever',
            field=models.CharField(blank=True, verbose_name=core.models.User),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
