# Generated by Django 4.2.4 on 2023-08-16 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_messages_reciever_chat_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='components',
        ),
        migrations.AddField(
            model_name='components',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.projects'),
        ),
    ]
