# Generated by Django 4.2.4 on 2023-08-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_projects_client_projects_file_projects_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='tags',
        ),
    ]
