# Generated by Django 4.2.4 on 2023-08-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('T', 'To-Do'), ('O', 'Ongoing'), ('C', 'Complete'), ('V', 'Verified')], default='T'),
        ),
    ]
